title: "Julián Roa-Rozo"
author: "Blog Author"
description: "Personal webpage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/roarozojulian/roarozojulian.github.io/raw/master/files/Julian_Roa_Rozo_CV_BM%20(12).pdf" , title: "CV"}
  - {file: "Research.html", title: "Research"}
  - {file: "Press.html", title: "Press articles"}
  - {file: "Julian_CV.pdf", title: "Output gaps data"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:julianroarozo@gmail.com"}
  - {title: Github, icon: github, url: "https://roarozojulian.github.io/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/rrjulian95"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
